### PR TITLE
Add information about Classifier header in Controller HTTP Endpoint

### PR DESCRIPTION
**Pull request by dragoangel**
Add information about `classifier` header in `/learnspam` and `/learnham` controller http endpoint.

### CODE REVIEW

**Comment by dragoangel** [comment]
@vstakhov @moisseev please verify if this update is correct. Also as I understand comments in code should be also fixed: https://github.com/rspamd/rspamd/blob/5a2dedd00eb68a5d4c7acda93fd3cc4f3bb2d358/src/controller.c#L2128-L2148

**Comment by dragoangel** [comment]
Also I think this will be more clear example: https://github.com/rspamd/rspamd/pull/5079/files

**Comment by dragoangel** [comment]
@moisseev thank you for a imprevements :)

**Review by vstakhov — APPROVED** [review]
LGTM!

**Pull request merged**
