### PR TITLE
Update statistics with per-domain example

### PR DESCRIPTION
**Pull request by dragoangel**
Add example of using LUA function to change behaviour of per-user statistics to per-domain. Also move per-user information to the bottom of the document, as this is big section that should be described better in the end of the page to not confuse people.

### CODE REVIEW

**Comment by dragoangel** [comment]
@moisseev can you please check if it good? 😊

**Comment by moisseev** [comment]
> is too old info from the times when sqlite was an option

SQLite is still supported by Rspamd. :(

**Comment by dragoangel** [comment]
I know but at same time it's doesn't described anywhere. I assume new users has not aware about it and always using redis. And by new users I mean people who using rspamd for 3+ years 😁

**Comment by dragoangel** [comment]
@moisseev can you please advice about `cache` option in `classifier`? It is should be set to `backend = "redis";` as per configwizard? But I also do not see mentioning it in the docs, should we add it or this is non needed thing?

**Comment by moisseev** [comment]
I have no idea what it is. I guess it's somehow related to learns cache.

**Review by vstakhov — APPROVED** [review]
It looks very good to me, thank you. It is much better than the original version, as it explains from the practical appliances how to use this feature.

**Pull request merged**
