### PR TITLE
Update dkim_signing.md

### PR DESCRIPTION
**Pull request by systemcrash**
Disable DKIM signing....

### CODE REVIEW

**Comment by vstakhov** [comment]
It is better to disable it by using `enabled = false`. However, I don't recommend to use side utilities for DKIM signing as Rspamd can do everything internally...

**Comment by systemcrash** [comment]
You're probably right - but this is the first place I've seen this documented. When I checked the config files, I found that to disable it, I had to do as I wrote in the initial PR. 

I've already committed to ODKIM in my infrastructure, although I could change at a later date. So documenting how to en/disable things is useful.

**Comment by systemcrash** [comment]
like so?

**Comment by vstakhov** [comment]
Yes, I agree, thank you.

**Pull request merged**
