### PR TITLE
Update razor documentation

### PR DESCRIPTION
**Pull request by defkev**
razorfy is obsolete

### CODE REVIEW

**Comment by slavkoja** [comment]
> naturally systemd will flag the unit as failed on a non-zero exit code which in this case just means the last scanned message was HAM.

Do you consider, that some systems does failed units monitoring? This will trigger it...

**Comment by defkev** [comment]
Only if you monitor disabled services, which wouldn't make a whole lot of sense to begin with.

**Comment by slavkoja** [comment]
Of course, i want to be notified eg. on failed timer's services too, and those services are not enabled.

**Comment by defkev** [comment]
If your *.timer fails the timer unit fails, similar if a *.socket fails.
It is possible to ignore the return code in ExecStart but i suppose then ExecPostStop never triggers...
I'll have to try this tomorrow.

**Comment by slavkoja** [comment]
I will try it latter, as i can easily break phpsessionclean.timer (or so) by running gparted ;-) but i am busy now with onother task...

**Comment by slavkoja** [comment]
The phpsessionclean.timer fails, not their service:
```
● phpsessionclean.timer - Clean PHP session files every 30 mins
     Loaded: loaded (/lib/systemd/system/phpsessionclean.timer; enabled; vendor preset: enabled)
     Active: failed (Result: resources) since Mon 2021-07-19 16:39:00 CEST; 21min ago
    Trigger: n/a
   Triggers: ● phpsessionclean.service

júl 19 09:08:54 bonifac systemd[1]: Started Clean PHP session files every 30 mins.
júl 19 16:39:00 bonifac systemd[1]: phpsessionclean.timer: Failed to queue unit startup job: Unit var.mount is masked.
júl 19 16:39:00 bonifac systemd[1]: phpsessionclean.timer: Failed with result 'resources'.
```

**Comment by defkev** [comment]
As was to be expected.

That being said, suppressing ExecStart will no longer trigger ExecPostStop, which is kinda silly of systemd but also expected.

But, razor@.service is a template, whereas your phpsessionclean.service is a unit, which brings me back to my original post wherever you really monitor templates.

e.g. razor@.service will never be called, razor.socket will call the template razor@.service as e.g. razor@8-127.0.0.1:11342-127.0.0.1:35596.service causing razor.socket to enter failed state if the template failed. (logged as an error in the journal)
Whereas if the template executes successfully it will either call ExecStop or ExecPostStop depending on ExceStart which in either case yields exit 0 (no error in the journal)

What monitoring are you using and does it really monitor templates?

**Comment by slavkoja** [comment]
Yes, you are right, the phpsessionclean was bad example. But today i encouter another one, with logrotate.timer:
```
● logrotate.timer - Daily rotation of log files
   Loaded: loaded (/lib/systemd/system/logrotate.timer; enabled; vendor preset: enabled)
   Active: active (waiting) since Tue 2021-07-20 09:49:28 CEST; 7min ago
  Trigger: Wed 2021-07-21 00:00:00 CEST; 14h left
  ...

● logrotate.service - Rotate log files
   Loaded: loaded (/lib/systemd/system/logrotate.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-07-20 09:49:41 CEST; 7min ago
  Process: 637 ExecStart=/usr/sbin/logrotate /etc/logrotate.conf (code=exited, status=1/FAILURE)
 Main PID: 637 (code=exited, status=1/FAILURE)
  ...
```
It is error which i exactly mean, timer is OK, but its service failed. My monitoring caught it, as you can see that it was investigated (and solved) 7 min after it happens.

IMO, it doesn't matter that it is template, AFAIK templates are used only to generate service file and that is called, the template itself is not used for any other purpose.

If any service fails, even runtime one, it stays in failed state until it is restarted (and success) or its failed state is reset, and thus will be reported by the `systemctl --failed` -- did you try it?

**Comment by defkev** [comment]
You are indeed correct and this would clutter up `--failed` pretty good with each consecutive HAM as each socket will spawn a new template.

The problem is that razor is working as intended as it is meant to be piped to something e.g. procmail.
Pyzor does the same but returns a metric of the scanned mail so you can ignore the exit code, whereas razor only returns something if you scan multiple mails at a time, returning the digest of detected mail(s).

I could pipe the output of razor-check to echo like:
```
#!/bin/bash
razor-check - && echo "spam" || echo "ham"
```
But systemd doesn't provide a shell which would mean adding another dependency i'd rather avoid.

I'll take another look.

**Comment by slavkoja** [comment]
Using BASH for it is overkill, use `/bin/sh`, while on some systems it still can be bash, it must be less resource hungry anyway.

IMO, simpler than use wrapper script can be to use `/bin/sh -c ...` directly in systemd unit, which must provide the same result without external script required.

**Pull request merged**
