### PR TITLE
neural.md: max_trains->max_train in conf snippets

### PR DESCRIPTION
**Pull request by larryhynes**
Unless I'm mistaken, this needs `max_train`, not `max_trains`

### CODE REVIEW

**Comment by vstakhov** [comment]
Well, actually `max_trains` was added after `max_train`:

```lua
  if rule_elt.train.max_train then
    rule_elt.train.max_trains = rule_elt.train.max_train
  end
```

And it is `max_trains` that is used commonly in the code. I'm not the native English speaker and I'm known for creating stupid and weird names so I have no strong opinion on that to be honest :)

**Comment by larryhynes** [comment]
I have a small installation, just a personal server. So I used to have `max_train = 20` in `local.d/neural.conf`.

Recently I tweaked that to `60`, but having looked at the docs, changed it to `max_trains = 60` (with the 's'). Even after 200+ trains, I got no `NEURAl_*` symbols or classification on incoming messages. Changed it back to 20, still no symbols.

Just today, I had the idea to change it back to `max_train = 20` (without the 's')... now I have proper `NEURAL` classification again.

So, I don't think using `max_trains` in `neural.conf` works! :) (At least, it doesn't for me, using `rspamd-2.5`).

**Comment by vstakhov** [comment]
You have revealed another issue in fact. Rspamd default config provides `max_train` option and it overrides unintentionally `max_trains` due to this legacy handling code. I have renamed the default and changed to a more safe legacy handling code. So I would suggest to use `max_trains` from the next version (2.6). This should be reflected in docs indeed.

**Comment by larryhynes** [comment]
OK. :) Thanks for looking into it. I'll close this.

**Pull request closed without merging**
