### PR TITLE
Add GTUBE-like test patterns list

### PR DESCRIPTION
**Pull request by moisseev**

### CODE REVIEW

**Comment by vstakhov** [comment]
Do you think it is worth tho place this information in the top menu? I'd suggest to remove it from the top menu and leave merely in the `developers docs` side section. Or even merge the whole section onto protocol documentation.

**Comment by moisseev** [comment]
I think users are more interested in this information rather than developers, so the `developers docs` is not appropriate place for that. I don't know were to place it. It seems there is no section for  such information yet.

**Comment by vstakhov** [comment]
Faq or protocol maybe?

**Comment by moisseev** [comment]
I don't see how it is related to protocol. FAQ seems better, but it is overloaded, I am afraid. Any topic that doesn't have a section goes to FAQ.

**Pull request merged**
