### PR TITLE
Random01

### PR DESCRIPTION
**Pull request by TonyGravagno**
Enhancements and updates for doc/modules/index.md.
Ref [discussion](https://github.com/rspamd/rspamd/discussions/3731) where I asked about how to submit a contribution like this. If the format here is not acceptable, please suggest a different approach and I'll comply.
If this PR is accepted, there are many more changes I'd like to submit for other pages. Thanks.

### CODE REVIEW

**Comment by TonyGravagno** [comment]
I accidentally pushed into the same branch twice. The first push is complete through "Update Lua modules...". The second starts with "Clarify". These are independent and non-conflicting.

**Comment by vstakhov** [comment]
Hello Tony,

Thank you for your hard work in polishing the documentation. It really needs more attention as I'm clearly not a native speaker and have some issues with written English. Do you prefer this PR to be merged or do you plan additional work on it? Github allows to mark PRs as `draft` should you want to merge multiple commits over the time in a single PR. I'm fine with either approach. Thanks again!

**Comment by TonyGravagno** [comment]
I sincerely appreciate the positive feedback, and understand the language issue. I made a [note of it](https://github.com/TonyGravagno/rspamd.com/pull/1) in my second not-yet-submitted PR.

I recommend creating a 'dev' branch for this repo. I can squash and submit one commit per (usually) one doc page. Rather than rejecting some commits, please merge all commits to **dev** as you go through them, noting comments and required corrections here for each commit. I'll submit new commits that fix issues with prior commits. Whenever it seems reasonable and all changes have been addressed, you can merge **dev** to **master** and we can close the current PR. This avoids the issue where rejected commits invalidate subsequent changes, and always leaves **master** stable.

I suggest refreshing the PRs frequently, maybe once per week. I'll submit a new one whenever you close the existing one. This will help to keep the chain of comments short and old discussions out of sight.

Overall, I'd like this to be as fluid as possible, so that I can quickly make changes and post updates here as I go through the docs. I'd also like this to be as fluid as possible for you, so that you can quickly go through the changes, post notes, and move on to more important work.

Please let me know what I can do to ensure your comfort with this process. Thanks.

**Comment by vstakhov** [comment]
Ok, I will merge this PR as I don't see any issues with it. WRT the dev branch: I think it is not needed as there are no CI/CD, the docs are just published from the git repo.

**Pull request merged**
